### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by rhzs** [Davide-Gheri/nestjs-mercurius#132]
I got error when building the project.

```
node_modules/nestjs-mercurius/node_modules/@apollo/gateway/src/make-fetch-happen.d.ts:58:18 - error TS2300: Duplicate identifier 'fetch'.

58   export default fetch;
                    ~~~~~

  node_modules/@apollo/gateway/src/make-fetch-happen.d.ts:58:18
    58   export default fetch;
                        ~~~~~
    'fetch' was also declared here.

node_modules/@apollo/gateway/src/make-fetch-happen.d.ts:58:18 - error TS2300: Duplicate identifier 'fetch'.

58   export default fetch;
                    ~~~~~

  node_modules/nestjs-mercurius/node_modules/@apollo/gateway/src/make-fetch-happen.d.ts:58:18
    58   export default fetch;
                        ~~~~~
    'fetch' was also declared here.


Found 9 errors.
```

Any idea how to fix the issue?

**Comment by Davide-Gheri** [comment]
Hi, you probably have some depencency version mismatch, I think it could be @nestjs/graphql.
This library uses the version `~7.10.6` but a new minor (`7.11.0`) was released just few days ago.
I think you have 2 different versions of it (and with it all its different dependencies, like @apollo/gateway)

If you use yarn check with:
`yarn why @apollo/gateway` and `yarn why @nests/graphql` and see how many versions you have installed.

To fix pin your @nestjs/graphql dependency to 7.10.6 and do a fresh install of all dependencies. It should fix the problem
