### ISSUE TITLE
Playground is not working

### ISSUE THREAD

**Issue by essarn** [Davide-Gheri/nestjs-mercurius#164]
Requesting `/playground` results in a `404` using `nestjs-mercurius": "^0.10.1`.

The module begins registred.
```typescript

MercuriusModule.forRoot({
  autoSchemaFile: 'schema.graphql',
  context: (_, reply) => ({
    reply,
  }),
}),

```

**Comment by Davide-Gheri** [comment]
The route is not always attached, you have to explicitly enable it with the property `graphiql`, setting it as `playground`:


```typescript
MercuriusModule.forRoot({
  ...
  graphiql: 'playground',
}),
```
