### ISSUE TITLE
Nest.js middleware does not execute when using nestjs-mercurius.

### ISSUE THREAD

**Issue by j** [Davide-Gheri/nestjs-mercurius#178]
I created an upstream issue because I thought it might be a Nest.js issue.  I'm not completely sure if it is or isn't.

https://github.com/nestjs/nest/issues/7569

and the reproduction... https://github.com/j/nestjs-middleware-bug

I'm uncertain and haven't dug too much into it, but it breaks my authentication when switching over to this library.  I'm assuming it might be due to the duplicate "fastify" modules you get when installing `@nestjs/platform-fastify` and (nestjs-)mercurius.

It's a pretty blocking issue though since a lot of people use modules that rely on nest application middleware.

**Comment by Davide-Gheri** [comment]
Checked, yup you're right, as a note, with Yarn works.
I'll remove entirely the `fastify` peerDep so the only one required is defined in `@nestjs/platform-fastify`

**Comment by j** [comment]
Yeah I've been using latest NPM for some reason and switched away from yarn and hit a bit of issues, haha.

Though strict isn't a bad thing and yarn not duping fastify could break things.

**Comment by j** [comment]
@Davide-Gheri Side note: I tried cloning this repository and can't install dependencies.  I can submit a PR with fixes and test if needed.
