### ISSUE TITLE
[Suggestion] - Ability to run two different paths (or more)

### ISSUE THREAD

**Issue by smolinari** [Davide-Gheri/nestjs-mercurius#279]
Hi,

With Mercurius, if you create two different Mercurius instances, it is possible to have two different paths (or more with more instances). For example, you could have most queries running over `./graphql` and have something like a refresh process (for jwt tokens) over  a `./refresh` path (for tighter security). 

Seems, if I try to do two different instances via `forRoot` with `nestjs-mercurius` the two instances both get the same schema defs causing a duplication error. 

I'm wondering, would it be feasible to add, similar to what Nest does (which also doesn't work for code-first), to include and/ or exclude certain schema defs in the `forRoot` config object?

For example, in the main instance you'd have:

```ts
@Module({
  imports: [
    // Work also with async configuration (MercuriusModule.forRootAsync)
    MercuriusModule.forRoot({
      path: './graphql`,
      exclude: [RefreshResolver],
      autoschemaFile: true,
      context: (request, reply) => ({
        user: request.user,
      }),
      subscription: {
        context: (connection, request) => ({
          user: request.user,
        }),
      },
    }),
  ],
  providers: [
    CatResolver,
  ],
})
export class AppModule {}

```

and in the other instance:

```ts
@Module({
  imports: [
    // Work also with async configuration (MercuriusModule.forRootAsync)
    MercuriusModule.forRoot({
      path: './refresh`,
      include: [RefreshResolver],
      autoschemaFile: true,
      context: (request, reply) => ({
        user: request.user,
      }),
    }),
  ]
})
export class AppModule {}

Scott

**Comment by Davide-Gheri** [comment]
It should be possible to have two (or more) graphql endpoints using Fastify encapsulation, see:
https://www.fastify.io/docs/latest/Encapsulation/ and https://github.com/mercurius-js/mercurius/issues/569

just by changing the way mercurius is registered:
in **base-mercurius.module.ts#registerFastify()**
```
await app.register(async (app) => {
  await app.register(mercurius, options);
  this.addHooks(app);
});
```

And then follow how `@nestjs/graphql` does, with the `include` property
https://docs.nestjs.com/graphql/quick-start#multiple-endpoints

Your example would then be:

```
@Module({
  providers: [
    RefreshResolver,
  ],
})
export class RefreshModule {}
```
```
@Module({
  providers: [
    CatResolver,
    DogResolver,
    // ... All other resolvers
  ],
})
export class MainModule {}
```

And in your `AppModule`
```
@Module({
  imports: [
    RefreshModule,
    MainModule,
    MercuriusModule.forRoot({
      include: [RefreshModule],
      prefix: '/refresh',
      path: '/',
      graphiql: true,
      autoSchemaFile: 'refresh-schema.graphql',
    }),
    MercuriusModule.forRoot({
      include: [MainModule],
      graphiql: true,
      autoSchemaFile: 'main-schema.graphql',
    })
  ]
})
export class AppModule {}
```

You will have `/graphql` (and `/graphiql` for GraphiQL UI) and `/refresh` (and `/refresh/graphiql`)

The main drawbacks I see right now are the usage of `GraphQLSchemaHost` (from `@nestjs/graphql`), it will be set with the last registered schema (main schema in this example).

Also the `app.graphql` decorator won't be globally available (as it is not directly registered to the fastify instance).
As an use case, getting the `pubsub` won't be possible outside the request context (ex using `PubSubHost#getInstance()`

**Comment by smolinari** [comment]
So, it's not quite a proper solution? You lost me on the last two sentences to be honest. 😊 

Scott

**Comment by Davide-Gheri** [comment]
if one would like to access the fastify decorators that mercurius adds (https://mercurius.dev/#/docs/api/options?id=decorators) it won't be possible because mercurius will be registered as a child plugin.

A reason to do this could be getting the pubsub instance (when subscriptions are enabled) where the current request context (`@Context()` decorator) is not available, for example wanting to publish something from a Nest Service that is not request scoped

**Comment by smolinari** [comment]
I definitely need `@Context`. I'll do some investigating and if it doesn't work as I need it, I'll try a hybrid API approach for my use case, where I'll just use a normal REST endpoint for the token refreshing. 

Closing the issue. 

Scott
